### ISSUE TITLE
Can you please specify library versions in the requirement files

### ISSUE THREAD

**Issue by SuperKogito** [castorini/honk#104]
The requirement files do not specify the versions of each library which is making it hard for me (and I assume for others) to run the code.

**Comment by ljj7975** [comment]
it seems to me that the [requirement.txt](https://github.com/castorini/honk/blob/master/requirements.txt) file already contains versions for each package.
What is the issue you are facing?

**Comment by SuperKogito** [comment]
I was referring to the [keyword_spotting_data_generator requirements file](https://github.com/castorini/honk/blob/master/keyword_spotting_data_generator/requirements.txt).
I am having the following problem with [pytube](https://github.com/nficano/pytube).
```
Traceback (most recent call last):
  File "keyword_data_generator.py", line 11, in <module>
    import pytube.YouTube as PyTube
  File "/home/kogito/anaconda3/envs/py37/lib/python3.7/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/home/kogito/anaconda3/envs/py37/lib/python3.7/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/home/kogito/anaconda3/envs/py37/lib/python3.7/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (/home/kogito/anaconda3/envs/py37/lib/python3.7/site-packages/pytube/compat.py)
```

**Comment by ljj7975** [comment]
This is what I have, I will add the versions to the requirement.txt soon
```
librosa                                0.6.2
pytube                                 9.5.2
requests                               2.21.0
inflect                                2.1.0
pocketsphinx                           0.1.15
google-api-python-client               1.7.11
pydub                                  0.23.1
```
Couple things to note:
- PyTube will be updated to PyTube3 soon (#101)
- Keyword Data Generator works but takes a long time to get a decent amount of data. Therefore, I would say it is still in dev.

**Comment by ljj7975** [comment]
Please let me know if the above versions work

**Comment by SuperKogito** [comment]
I was using `pytube==9.6.0`  but downgrading to `pytube==9.5.6` solved it for me. Thank you! :+1:  :smile:
