### ISSUE TITLE
Port TF audio ops to PyTorch

### ISSUE THREAD

**Issue by daemon** [castorini/honk#13]
Secondary objective is to port audio processing ops to PyTorch. Specifically, the following need to be implemented without third-party library support:
- FFT/STFT (inverse FFT isn't required)
- log-Mel filterbank
- fast DCT

torchaudio provides [a wrapper](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py#L129) of librosa's Mel spectrogram function (first two points). However, this implementation is claimed as relatively slow and non-GPU accelerated. It would be nice to implement the entire audio processing pipeline in a fast PyTorch-friendly manner.

**Comment by lintool** [comment]
> "... without third-party library support"

Why is this a requirement? We can have additional 3rd dependencies?

> "librosa's Mel spectrogram function"

Let's get something working first and then worry about speech?

**Comment by daemon** [comment]
Yeah, I was going to explore this objective after I get a working demo of the custom keyword stuff. What I mean regarding "without third-party library support" is that those 3 functions in particular should be implemented without other dependencies for better inclusion into torchaudio.

**Comment by lintool** [comment]
TF to PT port completed and merged as part of #16, #17, and #18 - all merged.
