### ISSUE TITLE
Explore Sphinx as an alternative backend for command triggering

### ISSUE THREAD

**Issue by lintool** [castorini/honk#15]
We've been using [Google's speech command dataset](https://research.googleblog.com/2017/08/launching-speech-commands-dataset.html) but we should explore Sphinx as well.

**Comment by daemon** [comment]
Right now, it seems like Sphinx is the more promising option for the following reasons:
- Requires less user training (probably 2-3 repetitions as opposed to 10)
- Requires less training time (adding a simple rule as opposed to 8 minutes)
- PocketSphinx is specifically tuned for less powerful devices

I'll continue porting the TF model to PyTorch.

**Comment by tuzhucheng** [comment]
@w268wang maybe you can summarize your findings here and we can close this issue?

**Comment by lintool** [comment]
Can we get this running on the RPi and see how it performs? (If it runs at all?)

**Comment by lintool** [comment]
@w268wang Can we compare Sphinx running on RPi vs. our CNN models in terms of power consumption?

**Comment by w268wang** [comment]
Sure, i ll try to set sphinx up on rpi tonight or tomorrow afternoon
