### ISSUE TITLE
Merge RPi power consumption scripts

### ISSUE THREAD

**Issue by lintool** [castorini/honk#29]
Merge the test harness and all code necessary to evaluate RPi power consumption of various CNNs.

**Comment by tuzhucheng** [comment]
First step, @daemon please create PR to merge the latest service.py from your Caffe2 service branch into master?

**Comment by tuzhucheng** [comment]
@w268wang I pushed the scripts you wrote into the `rpi-experiments` branch and amended you as commit author. Please refactor the code and then make a PR?

* Remove all hardcoded IP address & port number - supply them from `argparse` with reasonable default for port
* Upgrade code to Python 3 if possible - if the Wattsup meter stuff cannot be done with Python 3 at least change the `print` statements to `print` function calls
* Write README.md documentation for how to use it

**Comment by w268wang** [comment]
Sure, I ll do that tonight or tomorrow morning
and @tuzhucheng I remember when I tried to write this script there is a step will cause some error when running with Python 3. I will give it another try though.

**Comment by tuzhucheng** [comment]
Cool, after you are done I'll merge in the Jupyter notebook & R script for creating our charts into the same folder.

**Comment by w268wang** [comment]
sounds good
