### ISSUE TITLE
How to calculate False alarm rate and false rejection rate

### ISSUE THREAD

**Issue by z430** [castorini/honk#37]
Hi, 
thank you for sharing the code
I am a bit curious about how you calculate the false alarm and false rejection rate like in your paper.
I hope you can tell me how to do it

**Comment by daemon** [comment]
Sorry for the late reply.

Unfortunately, I don't have the code for drawing the ROC curves anymore. Here are a few pointers in the right direction:
[https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42537.pdf](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42537.pdf)
[https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43969.pdf](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43969.pdf)
