### ISSUE TITLE
Logo Proposal for Honk

### ISSUE THREAD

**Issue by zuurw** [castorini/honk#48]
Hello, as you requested I create this design for Honk, see if you like it.

![logo proposal](https://user-images.githubusercontent.com/40801473/42423120-a72a019c-82ec-11e8-9804-48cfa3941542.png)

**Comment by daemon** [comment]
We really like the B&W one! Can you include the Illustrator files as well in the PR? Thanks again for your contributions.

**Comment by zuurw** [comment]
Great, I will do that in the PR.

Greetings!

**Comment by zuurw** [comment]
I saw that you have lots of projects, It will be a pleasure to me to create a design for that projects too.

If you want just say it, Im here to help!

Cheers!

**Comment by lintool** [comment]
Hi @zuurw Thanks so much for your contributions!

Our group has two addition projects - http://anserini.io/ and http://castor.io/

Anserini is a [goose](https://en.wikipedia.org/wiki/Anser_(bird)) and Castor is a [beaver](https://en.wikipedia.org/wiki/Beaver).

The two systems were designed to work together, with Castor using data provided by Anserini. We were very much inspired by this image: https://i.pinimg.com/736x/2c/27/c4/2c27c40aca3a3e041ad3c588cc03f9cf--beavers-flags.jpg

Might you design two logos for us that would work separately (for each individual project), as well as together, for https://github.com/castorini

Finally, we'd like to acknowledge your contribution by linking back to you for all our logos - what should we link back to? Your GitHub page?

Thanks so much!

**Comment by zuurw** [comment]
Hello,
I try to see the link for the image, but it doesnt show nothing, can you send me the image.
Thank You!

**Comment by lintool** [comment]
Fixed link above!

**Comment by zuurw** [comment]
I saw the Image It´s really nice :) but at the same time it will be a challenge for me.
Does they have some licence the two projects?
I will close this issue and open a new one in this two repositories, can I do that?
I create the PR for honk with all the files.

Cheers!
