### ISSUE TITLE
How to train to reproduce the performance

### ISSUE THREAD

**Issue by tonysy** [castorini/honk#54]
Thanks for your work.
If I want use cnn-trad-pool2 model to train, what's the exact training parameters. 

Does the following command from your readme is suitable for cnn-trad-pool2 model?
```
python -m utils.train --wanted_words yes no up down left right on off stop go --dev_every 1 --n_labels 12 --n_epochs 26 --weight_decay 0.00001 --lr 0.1 0.01 0.001 --schedule 3000 6000 --model res{8,15,26}[-narrow]
```

Thanks.

**Comment by daemon** [comment]
Thanks for your interest. Yep, passing in the corresponding model name (`cnn-trad-pool2`) for the `--model` option should work.
