### ISSUE TITLE
Support a Mac?

### ISSUE THREAD

**Issue by torntrousers** [castorini/honk#55]
Thanks for the great work. Any chance this could be made to work on a Mac? I don't have a linux machine and initially don't want to faff around with a Pi.

**Comment by daemon** [comment]
Thanks for your interest. I believe it _should_ work relatively easily on a Mac, since PyTorch has Mac support.

**Comment by torntrousers** [comment]
Could you give me any tips on how to do it?

**Comment by daemon** [comment]
For PyTorch, the official documentation is [here](https://pytorch.org). You can scroll down to see installation instructions on Mac. However, you'd be limited to the CPU-only version (I think), which precludes much faster GPU-based routines. Our readme also has this notice for Macs:
> Additional notes for Mac OS X:
> GLUT is already installed on Mac OS X, so that step isn't needed.
> If you have issues installing pyaudio, this may be the issue.
