### ISSUE TITLE
How to calculate number of multiplies?

### ISSUE THREAD

**Issue by justin-hpcnt** [castorini/honk#81]
I found the number of parameters and multiplies at the paper.

Even tough I check most of the code base, I couldn't find out a snippet that measures it.

Would you please tell me how to calculate it?

**Comment by daemon** [comment]
I calculated those manually. Following Sainath and Parada's CNN paper, I assumed a naive convolution algorithm, which is basically im2col and then a naive matrix multiply.

**Comment by justin-hpcnt** [comment]
Thanks :D
