### ISSUE TITLE
Where is the google-speech-dataset.pt ?

### ISSUE THREAD

**Issue by azuredream** [castorini/honk#85]
There is not a google-speech-dataset.pt which needed by the server.py in model.zip. I tried to get it by "python -m utils.train --data_folder ./training_data --type train", but I got a "model.pt" . Even I rename it and run "python .", an error will arise as below.

RuntimeError: Error(s) in loading state_dict for SpeechModel:
        size mismatch for output.weight: copying a param of torch.Size([12, 26624]) from checkpoihe shape is torch.Size([4, 26624]) in current model.
        size mismatch for output.bias: copying a param of torch.Size([12]) from checkpoint, whereis torch.Size([4]) in current model.

**Comment by azuredream** [comment]
Should I add some paras into the config.json ?

**Comment by daemon** [comment]
We mistakenly deleted `google-speech-dataset.pt` from https://github.com/castorini/honk-models -- it's fixed now. I believe that error results from not specifying `n_labels` as `12` (keywords).

**Comment by azuredream** [comment]
Thanks for your help, it's working :D
