### ISSUE TITLE
Compare vs. existing projects

### ISSUE THREAD

**Issue by lintool** [castorini/honk#9]
I did a quick search and found several other projects that have similar goals. We should find out if we're reinventing the wheel:

+ [Jasper](https://jasperproject.github.io/)
+ [baluubas/voice-command](https://github.com/baluubas/voice-command)
+ [baitsart/voice-commands](https://github.com/baitsart/voice-commands)

**Comment by daemon** [comment]
I took a brief look, I think Jasper comes closest.

Jasper
- idea is Alexa platform but FOSS on RPi
- supports custom hotword https://github.com/jasperproject/jasper-client/issues/8
- fully local speech recognition

baluubas/voice-command
- uses local desktop OS speech recognition
- no hotword support, but that was a design choice

baitsart/voice-commands
- purely shell
- sends everything to Google STT to detect command

**Comment by lintool** [comment]
Closing since we've decided to proceed with Google's TF model, and we have a successful PT port. Sphinx alternative still viable, still exploring as part of #15
