### ISSUE TITLE
How to get an uncertain length of audio into the model

### ISSUE THREAD

**Issue by aaab8b** [castorini/honk#90]
i was trying to feed some audio data from my own into the pretrained model, however, it seems like the tensor shape can only be (101,40), how should i resize my own data to such shape like that with uncertain length?

**Comment by daemon** [comment]
The typical approach is to chop up the audio into fixed, overlapping windows, and then perform keyword spotting on each. To adjust the false alarm rate, you can compute and threshold a confidence score from multiple windows -- see [this seminal paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42537.pdf).
