### ISSUE TITLE
Unable to install `PyOpenGL_accelerate` on MacOS Mojave

### ISSUE THREAD

**Issue by harritaylor** [castorini/honk#92]
Here is the error:
`    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/ww/cclx4hb97_q6dbmy_srts9mr0000gp/T/pip-install-ndyalced/PyOpenGL-accelerate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ww/cclx4hb97_q6dbmy_srts9mr0000gp/T/pip-record-1qhkmp0n/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ww/cclx4hb97_q6dbmy_srts9mr0000gp/T/pip-install-ndyalced/PyOpenGL-accelerate/`

I can't find any info on how to get it installed on MacOS, any ideas?

**Comment by daemon** [comment]
It doesn't seem like people have gotten it working: https://github.com/pypa/pip/issues/6420. Maybe try Python 3.6?

**Comment by harritaylor** [comment]
Yep, seems to work when using `3.6.9`. Closing as it's not an issue with honk. Thanks.
