### ISSUE TITLE
an error has occured while processing video HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by JeongJin984** [castorini/honk#94]
def retrieve_keyword_audio(vid, keyword):
    audio_index = 0
    v_url = URL_TEMPLATE.format(vid)
    youtube = YouTube(v_url)

    y_len = youtube.player_config_args['player_response']['videoDetails']['lengthSeconds']
    print("Length:", y_len)
    print("Views:", youtube.views)

    if int(y_len) > 2700:
        # only consider video < 45 mins
        return audio_index

i got an error with length of video so i modifed code of keyword_data_generator.py 
but i got error named "HTTP Error 429: Too Many Requests"
how can i solve this problem(help me)

**Comment by daemon** [comment]
I think you're hitting the rate limit? @ljj7975 can probably help more.

**Comment by ljj7975** [comment]
First of all, this keyword collecting code is not complete yet.

Based on your error message, it seems to me that you are over the limit for YoutubeDataAPI.
I would first check whether you are within the limit or not.

Next, that YouTube object is defined in pytube library (https://github.com/nficano/pytube).
So I would check their code for further debugging!
